# Generated by Django 4.2.6 on 2024-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_watejawote_sikuyakupokea_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatatizoYaWateja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaMteja', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina La Mteja')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Ya Simu')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Yako')),
                ('Mkoa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mkoa')),
                ('Wilaya', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya')),
                ('Message', models.TextField(blank=True, max_length=10000, null=True)),
                ('is_checked', models.BooleanField(blank=True, default=False, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Matatizo Ya Wateja',
            },
        ),
        migrations.CreateModel(
            name='NotepadMatatizo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tatizo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina La Tatizo')),
                ('NambaYaTatizo', models.IntegerField(blank=True, null=True, verbose_name='Namba Ya Tatizo')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notepad Matatizo',
            },
        ),
        migrations.CreateModel(
            name='NotepadMikoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaLaMkoa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jina La Mkoa')),
                ('NambaYaMkoa', models.IntegerField(blank=True, null=True, verbose_name='Namba Ya Mkoa')),
                ('Kanda', models.CharField(blank=True, max_length=500, null=True, verbose_name='Kanda')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notepad Mikoa',
            },
        ),
    ]
