# Generated by Django 4.2.6 on 2024-10-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_matatizoyawateja_notepadmatatizo_notepadmikoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matatizoyawateja',
            name='JinaLaTatizo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Jina La Tatizo'),
        ),
    ]
