# Generated by Django 4.2.6 on 2024-10-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='MyPostID',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Ya Post'),
        ),
    ]
