# Generated by Django 4.2.6 on 2024-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_dukalako_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='SenderEmail',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email Ya Sender'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='SenderImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Picha Ya Sender'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='SenderPhone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Namba Ya Sender'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='SenderWilaya',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Wilaya Ya Sender'),
        ),
    ]
