# Generated by Django 4.2.6 on 2024-10-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_chatmessage_senderemail_chatmessage_senderimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sender Name'),
        ),
    ]
