# Generated by Django 4.2.6 on 2024-10-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replyTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='App.chatmessage'),
        ),
    ]
