# Generated by Django 4.2.6 on 2024-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_chatmessage_replyto'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
