# Generated by Django 4.2.6 on 2024-12-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_malipoyafainicopies_marejeshocopies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watejawote2',
            name='is_red',
        ),
        migrations.RemoveField(
            model_name='watejawote2',
            name='time_left',
        ),
    ]
