# Generated by Django 4.2.6 on 2025-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_smstoparticularusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstoparticularusers',
            name='JinaKamiliLaMteja',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Kamili La Mteja'),
        ),
        migrations.AddField(
            model_name='smstoparticularusers',
            name='Mahali',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mahali Anapoishi'),
        ),
        migrations.AddField(
            model_name='smstoparticularusers',
            name='SimuYaMteja',
            field=models.IntegerField(blank=True, null=True, verbose_name='Namba Ya Simu Ya Mteja'),
        ),
    ]
