# Generated by Django 4.2.6 on 2025-04-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_smstoparticularusers_jinakamililamteja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainazakuku',
            name='BeiYaKiloMoja_FinisherFeed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bei Ya Kilo Moja Chakula Cha Finisher'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='BeiYaKiloMoja_GrowerFeed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bei Ya Kilo Moja Chakula Cha Grower'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='BeiYaKiloMoja_LayerFeed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bei Ya Kilo Moja Chakula Cha Layer'),
        ),
        migrations.AddField(
            model_name='ainazakuku',
            name='BeiYaKiloMoja_StarterFeed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bei Ya Kilo Moja Chakula Cha Stater'),
        ),
    ]
