# Generated by Django 4.2.6 on 2025-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_ainazakuku_beiyakilomoja_finisherfeed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='middle_name',
        ),
    ]
